config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  get 'home' => 'home#index'
  get 'search' => 'home#search'
  get 'home/category/:id' => 'home#category_products', as: :user_category
  get 'home/product/:id' => 'home#product', as: :user_product

  get 'home/product/reviews/:id' => 'reviews#index', as: :product_reviews
  post 'home/product/reviews/:id' => 'reviews#create'

  get 'home/product/cart/:id' => 'carts#add', as: :add_user_cart
  get 'cart' => 'carts#index', as: :carts
  delete 'cart/:id' => 'carts#destroy', as: :cart

  resources :products, :categories

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  belongs_to :order
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :carts
  has_many :reviews
  has_many :users, through: :carts
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, through: :carts
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.where(user_id: 1)
  end

  def add
    user_id = 1 #its a sample id
    @cart = Cart.where("user_id = ? AND product_id = ?", user_id, params[:id])

    if(@cart.length.zero?)
      @cart = Cart.new
      @cart.user_id = user_id
      @cart.product_id = params[:id]
      @cart.unit = 1
    else
      @cart = @cart.first
      @cart.unit = @cart.unit + 1
    end

    save_item
  end

  def destroy
    user_id = 1
    @cart = Cart.where("user_id = ? AND product_id = ?", user_id, params[:id])
    @cart.delete_all

    redirect_to(:back)
  end

  private

    def cart_params
      params.require(:cart).permit(:product_id)
    end

    def save_item
      if @cart.save
        flash[:success] = "Added to Cart Successfully"
        redirect_to(:back) #product_reviews_path(@product)
      else
        render 'index'
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category Created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @categories = Category.all
    @cart_count = Cart.where("user_id = ?", 1).count
  end

  def category_products
    @products = Category.find(params[:id]).products
  end

  def product
    @product = Product.find(params[:id])
  end

  def search
    product_table = Product.arel_table
    @products = Product.where(product_table[:name].matches(search_argument))
  end

  def search_argument
    "%#{params[:search][:query]}%"
  end
end

app/controllers/kyc_controller.rb
class KycController < ApplicationController
  def index
    @investor = OpenStruct.new(
                              name: 'KIFER SUTHERLAND AKA JACK BAUER',
                              father_name: 'KIFER SUTHERLAND',
                              gender: 'male',
                              marital_status: 'single',
                              nationality: 'India',
                              status: 'Foreign National',
                              aadhaar: 'ABCD1234',
                              proof_identity: 'UID',
                              dob: '20101960',
                              pan: 'AKGBH1234A',
                              place: 'Bangalore',
                              date: '10102016',
                              ipv_status: 'Done',
                              ipv_date: '10102016',
                              email: "abcdkyc.com",

                              telephone_office: '9876543210',
                              telephone_residence: '1234567890',
                              fax: '5432112345',
                              mobile: '1234512345',

                              current_address: {
                                address: 'CYBRILLA TECHNOLOGIES, HSR LAYOUT 27TH MAIN ROAD',
                                pincode: '222001',
                                city: 'BANGALORE',
                                state: 'KARNATAKA',
                                country: 'INDIA',
                                proof: 'Passport',
                                proof_expiry_date: '10102015'
                              },

                              permanent_address: {
                                address: 'RED COTTON BUILDING NO. 10 OFF HUALEI ROAD',
                                pincode: '222001',
                                city: 'GUANGHZOU',
                                state: 'SOUTH CHINA',
                                country: 'CHINA',
                                proof: 'Passport',
                                proof_expiry_date: '10102015'
                              },

                              original_verified: 'Done',
                              original_attested: 'Done')

   respond_to do |format|
     format.html
     format.pdf do
       render pdf: "kyc",         # file name
              template: 'kyc/index.html.erb'
       end
     end
   end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def place
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @categories = Category.order(:name)
  end

  def index
    @products = Product.all

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ProductsPdf.new(@products)
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf',
                  disposition: "inline"
      end
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  def create
    @category = Category.find(params[:product][:category_id])
    @product = @category.products.build(product_params)

    if @product.save
      flash[:success] = "Product Created"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Product.find(params[:id]).reviews
    @product_id = params[:id]
  end

  def create
    @product = Product.find(params[:review][:product_id])
    @review = @product.reviews.build(review_params)

    if @review.save
      flash[:success] = "Review Submitted Successfully"
      redirect_to product_reviews_path(@product)
    else
      render 'index'
    end
  end

  private

    def review_params
      params.require(:review).permit(:comment, :rating, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-6">
      <h4>Cart</h4>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-striped table-hover">
        <tr>
          <th>Product Name</th>
          <th>Price</th>
          <th>Unit</th>
          <th>Sub Total</th>
          <th></th>
        </tr>

        <% @carts.each do |cart| %>
          <tr>
            <td> <%= cart.product.name %> </td>
            <td> <%= cart.product.price %> </td>
            <td> <%= cart.unit%> </td>
            <td> <%= cart.unit * cart.product.price %> </td>
            <td> <%= link_to "Delete", cart_path(cart.product.id),
                     method: :delete,
                     data: {confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to 'Place Order', home_path , class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Option</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td> <%= category.name %> </td>
      <td> <%= link_to "Delete", category_path(category),
               method: :delete,
               data: {confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add Category', new_category_path %>

app/views/categories/new.html.erb
Add new Category
<%= form_for :category, url: categories_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </p>

  <p>
    <%= f.submit%>
  </p>
<% end %>
<% link_to "Back", categories_path %>

app/views/home/category_products.html.erb
<h1>All Products</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td> <%= link_to product.name, user_product_path(product) %> </td>
      <td> <%= product.description %> </td>
      <td> <%= product.price %> </td>
      <td> <%= link_to "Add to Cart" %></td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<%= form_for :search, url: search_path, method: :get, :html => { :class => "form-horizontal" } do |f| %>
  <p>
    <%= f.text_field :query %>
    <%= f.submit "Search"%>
  </p>
<% end %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShopKart</a>
    </div>
    <ul class="nav navbar-nav">
      <% @categories.each do |category| %>
        <li><%= link_to category.name, user_category_path(category) %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Cart (#{@cart_count})", carts_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path %></li>
    </ul>
  </div>
</nav>

app/views/home/product.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><strong>Description</strong></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><strong>Price</strong></td>
          <td><%= @product.price %></td>
        </tr>
        <tr>
          <td><%= link_to "Add to Cart", add_user_cart_path(@product), class: "btn btn-primary"%></td>
          <td><%= link_to "Reviews", product_reviews_path(@product), class: "btn btn-primary" %></td>
        </tr>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td> <%= link_to product.name, product_path(product)%></td>
      <td> <%= product.description %> </td>
      <td> <%= product.price %> </td>
    </tr>
  <% end %>
</table>

app/views/products/index.html.erb
<h1>All Products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td> <%= product.name %> </td>
      <td> <%= product.description %> </td>
      <td> <%= product.price %> </td>
      <td> <%= link_to "Delete", product_path(product),
               method: :delete,
               data: {confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add Product', new_product_path %><br><br>
<%= link_to 'Printable Reciept(PDF)', products_path(format: :pdf)%>

app/views/products/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Add new Product</h4>
    </div>
  </div>
<%= form_for :product, url: products_path,:html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-group">
      <%= f.label :name,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :description,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-md-4 control-label" %><br>
    <div class="col-md-4">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category, class: "col-md-4 control-label" %><br>
    <div class="col-md-8">
      <%= collection_select(:product, :category_id, @categories, :id, :name, {:prompt => false}) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>
<% end %>
</div>
<% link_to "Back", products_path  %>

app/views/products/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><strong>Description</strong></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><strong>Price</strong></td>
          <td><%= @product.price %></td>
        </tr>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      Reviews
      <table class="table">
        <tr>
          <th>Comment</th>
          <th>Rating</th>
        </tr>
        <% @reviews.each do |review| %>
          <tr>
            <td> <%= review.comment %> </td>
            <td> <%= review.rating %></td>
          </tr>
        <% end %>
    </div>
    <div class="col-lg-6">
    </div>
    <div class="row">
      <div class="col-md-6 ">
    Write a Review

    <%= form_for :review, url: product_reviews_path do |f| %>
    <%= f.hidden_field :product_id, :value => @product_id %>
    <p>
      <%= f.label :comment %><br>
      <%= f.text_area :comment%>
    </p>

    <p>
      <%= f.label :rating %><br>
      <%= f.select :rating, options_for_select(1..5)%>
    </p>

    <p>
      <%= f.submit%>
    </p>
    <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>